services:
  # Database Service
  postgres-db:
    image: postgres:18-alpine
    container_name: postgres-inventory
    environment:
      POSTGRES_DB: mystore_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password_here
      PGDATA: /var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  # Kafka Broker
  broker:
    image: apache/kafka:4.1.1
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  # Kafka UI (Web interface at http://localhost:8090)
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8090:8080"
    depends_on:
      - broker
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: broker:9092

  # Spring Boot Application Service
  payment-inventory-service:
    build: .
    container_name: payment-inventory-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - broker
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/mystore_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: your_password_here
      # Kafka connection for the app inside Docker
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:9092
      SPRING_FLYWAY_ENABLED: "true"

volumes:
  postgres_data: